sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: T+EGi0OjB9nyRuKrcZlFNC9tdQrqL1jKPvyE6MlL2DpJQ7n/64Ol0OyoQxw5dTGcxQSlbvLcw4+BACKCgUTLrnaE0mGJW9lJWlFynb9ZvqWQJUjaL1CdojXw6dcGlJQJx8IARMv2SrMEaFsRayCOzxgkG0tYIfk2TxNJekzjZEpAQkW9idh33mI+nZgOBzaLYdqZ57JBWHltZM7zzt7gO/QaETZnoFefioMiougC2KuLyFx4A1lcsDr66Ubdcnt7tW/gYArktnYBzVf6DZG/C/CyvZiBLHO3bsDb1qQ9ip7SQcvXQm6WfRHc30inkYRbj8bgoJ/j2UOBfeYEoMRzFcSu3ql6+0AG/AAlLrJzPpuvD0y+sAA76O8k35y0WCmhGCZ1MPDgfnxD8eV5Dipnn3h39qEXV6vsOl/9BQHqzYpCtQCPsh/NCepXnHvP4YUvcgVpX80ic1FK2v8d2n/XbQsW916vi+n/JM+dZL2L0Ut6cRco+aw0THzmPQqCObijiB0OCH1uO6E3RALzk1BEMWZN+be0M+/N/ec3Lz0SAr5bStK6/m0rw9od38R3BzkKdDBBOuscq/2kvOYEakhVmrup0kixwOOu+/degZ1jHV0ZTeofu+xJmoVCbuVcpJNChL4Kz0HYjLO5IeGC7XAM3NdLXkMIHRp9LAlUDSfTW3Q=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Mein-Leben-und-Streben_2779
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy